### ISSUE TITLE
misused double quotes lead to error on PostgreSQL

### ISSUE THREAD

**Issue by KinIcy** [nykula/connect-typeorm#11]
By executing the following line, the resulted expression contains double quotes `"` that lead to an error on PostgreSQL. 

https://github.com/nykula/connect-typeorm/blob/6723f9963d437681c1e4ac6389ed8caec11b4683/src/app/TypeormStore/TypeormStore.ts#L109

On Postgres, the double quotes are used to escape identifiers meanwhile single quotes are used to escape values.

**Comment by nykula** [comment]
Try 4be05e1 locally? Would appreciate if you added an automated test.

**Comment by KinIcy** [comment]
Hello, I tested this locally and it worked. I don't know how to write a
test for this issue.

**Comment by nykula** [comment]
Ok. Released as v1.1.3.
