### ISSUE TITLE
Question about the Bigint transformer in the README

### ISSUE THREAD

**Issue by yagoferrer** [nykula/connect-typeorm#12]
Hi Denys, Nice TypeORM - Session Express integration! I'm going to start using it on one of my projects. 
I have a quick question about the documentation:

What is the benefit of using transformer: `Bigint`?  
```@Column("bigint", { transformer: Bigint })```

instead of: 
```@Column('bigint')```

`typeorm-static` Is a nice library but I feel that it should be optional and independent from `connect-typeorm` documentation examples. What do you think? I sent you a PR if you like the idea of changing this :)

Thanks!

**Comment by nykula** [comment]
Thank you for your suggestion and work. Answered in #13 next to the lines which need some changes before I can merge them.

**Comment by yagoferrer** [comment]
Thank you. I wrote some comments in #13
