### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by binki** [nykula/connect-typeorm#4]
The tests should exercise all public functions for all supported versions of typeorm and test the package as a “real” install. I may try contributing something if I can figure it out.

**Comment by makepost** [comment]
What tooling would you recommend for testing against multiple dependency versions? I know about [test-all-versions](https://www.npmjs.com/package/test-all-versions), haven't used it yet though.

**Comment by makepost** [comment]
Running SQLite in memory, without "real" side effects, is a good fit for atomic tests with Ava. [Experimented](https://github.com/makepost/380ch-api#atomic-tests) with exactly this, following the same reasoning you describe. Seems logical to have tests before moving on to #5 so I'll see what I can do. Thanks for staying in touch!
